<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccounttypeSeeder extends Seeder
{
    public function run()
    {
        $array = ([
            [
                'account_type_id' => 'FDDA5B70-421A-11EC-A70A-5FD74528FECD',
                'account_group_id' => '9F1D02A0-421A-11EC-92A6-BB4CCAAF9B33',
                'acc_code' => '0001',
                'acc_name' => 'PPF Received A/c',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Received Account',
            ],
            [
                'account_type_id' => '28179D20-421B-11EC-A240-2781FA47938F',
                'account_group_id' => '9F1D02A0-421A-11EC-92A6-BB4CCAAF9B33',
                'acc_code' => '0002',
                'acc_name' => 'PPF Collection A/c',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Collection Account',
            ],
            [
                'account_type_id' => '379A35D0-C3BB-11EC-B51B-79FB79A98A69',
                'account_group_id' => '9F1D02A0-421A-11EC-92A6-BB4CCAAF9B33',
                'acc_code' => '0003',
                'acc_name' => 'GF Received A/c',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Received A/c',
            ],
            [
                'account_type_id' => 'A8CE35A0-C3BB-11EC-BBC4-5976BCDF5AAA',
                'account_group_id' => '9F1D02A0-421A-11EC-92A6-BB4CCAAF9B33',
                'acc_code' => '0004',
                'acc_name' => 'GF Collection A/c',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Collection A/c',
            ],
            [
                'account_type_id' => '68015740-421B-11EC-BD82-255A432045D0',
                'account_group_id' => 'A7621450-421A-11EC-858F-9BE7FA733BC4',
                'acc_code' => '0005',
                'acc_name' => '200229748',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => 1,
                'acc_description' => 'Thimphu Collection Account',
            ],
            [
                'account_type_id' => '7E65C280-421B-11EC-9E0A-A5A7A15F7620',
                'account_group_id' => 'A7621450-421A-11EC-858F-9BE7FA733BC4',
                'acc_code' => '0006',
                'acc_name' => '29845639',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => 3,
                'acc_description' => 'Wangdi Collection Account',
            ],
            [
                'account_type_id' => '991D8F10-421B-11EC-AA4E-155C4EF47952',
                'account_group_id' => 'A7621450-421A-11EC-858F-9BE7FA733BC4',
                'acc_code' => '0007',
                'acc_name' => '388456374',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => 4,
                'acc_description' => 'Paro Collection Account',
            ],
            [
                'account_type_id' => 'E95B7070-421B-11EC-A8F2-819ABFC6F02F',
                'account_group_id' => 'B0B731C0-421A-11EC-B589-354B57453CBA',
                'acc_code' => '0008',
                'acc_name' => 'Cash A/c',
                'acc_nature' => 'Liability',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'Cash A/c',
            ],
            [
                'account_type_id' => 'EC1F47D0-45DE-11EC-A62C-C9CBDDDD92DE',
                'account_group_id' => '5A3C8E80-45DE-11EC-A079-D9F2813EF00D',
                'acc_code' => '0009',
                'acc_name' => 'PPF Interest Paid A/c',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Interest Paid A/c',
            ],
            [
                'account_type_id' => '02438250-C3BC-11EC-A142-EF0DDDCC0F8E',
                'account_group_id' => '5A3C8E80-45DE-11EC-A079-D9F2813EF00D',
                'acc_code' => '0010',
                'acc_name' => 'GF Interest Paid A/c',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Interest Paid A/c',
            ],
            [
                'account_type_id' => '57947520-45DF-11EC-9855-215ABC215B21',
                'account_group_id' => '785E1CF0-45DE-11EC-A4C9-0D3C9D51C511',
                'acc_code' => '0011',
                'acc_name' => 'PPF Interest Payable A/c',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Interest Payable A/c',
            ],
            [
                'account_type_id' => '50115C20-C3BC-11EC-8808-D9088D57FFC1',
                'account_group_id' => '785E1CF0-45DE-11EC-A4C9-0D3C9D51C511',
                'acc_code' => '0012',
                'acc_name' => 'GF Interest Payable A/c',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Interest Payable A/c',
            ],
            [
                'account_type_id' => '7BC4A9C0-45DF-11EC-8FB0-7BE4C3E060D0',
                'account_group_id' => '87AEC410-45DE-11EC-8103-D1EB6ECDC7A5',
                'acc_code' => '0013',
                'acc_name' => 'Profit and Loss A/c',
                'acc_nature' => 'Assets',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'Profit and Loss A/c',
            ],
            [
                'account_type_id' => 'A5C730C0-45DF-11EC-AAE3-1D943BCC8402',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0014',
                'acc_name' => 'PPF Collection Refund Payable',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Collection Refund Payable',
            ],
            [
                'account_type_id' => 'A2AC6540-C3BC-11EC-A548-07FC7107F9BF',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0015',
                'acc_name' => 'GF Collection Refund Payable',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Collection Refund Payable',
            ],
            [
                'account_type_id' => 'B68C9880-45DF-11EC-B0EC-4568E1C45C9C',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0016',
                'acc_name' => 'PPF Interest Refund Payable',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PPF Interest Refund Payable',
            ],
            [
                'account_type_id' => '176CD330-C3BD-11EC-8C43-83D7FBDFBAA0',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0017',
                'acc_name' => 'GF Interest Refund Payable',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Interest Refund Payable',
            ],
            [
                'account_type_id' => 'AAE231D0-C525-11EC-99CE-71ED67D278D2',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0018',
                'acc_name' => 'PF Excess Payment Account',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'PF Excess Payment Account',
            ],
            [
                'account_type_id' => '5AE5E410-C53C-11EC-90F3-799F616C2F34',
                'account_group_id' => '987A9B20-45DE-11EC-973C-47DC726D5DD3',
                'acc_code' => '0019',
                'acc_name' => 'GF Excess Payment Account',
                'acc_nature' => 'Expenses',
                'acc_sub_ledger' => NULL,
                'acc_branch_id' => NULL,
                'acc_description' => 'GF Excess Payment Account',
            ]
        ]);

        foreach ($array as $key => $rows) {
            DB::table('accounttypes')->insert($rows);
        }
    }
}
